flutter-base:
  fullnameOverride: client-web
  nameOverride: client-web
  replicaCount: 1
  image:
    repository: ghcr.io/isitgone/client
    tag: 90301a3cd4edcd5a4d2116ff8c7bcfa75bec42cc
  ingress:
    host: dev.isitgone.site
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
