flutter-base:
  fullnameOverride: client-web
  nameOverride: client-web
  replicaCount: 1
  image:
    repository: ghcr.io/isitgone/client
    tag: 43d1f0353226f4fd35a29d6c8c9ae50e3ccd022d
  ingress:
    host: dev.isitgone.site
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
