apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: graphql
  namespace: dev
spec:
  encryptedData:
    DB_URI: AgCMwEU4bJtXWV6Vc1VOvJHwyFP93EpwsZGDMGZXXDNSqcxyjaq70//+Q4Cd4qGNKLmx/VzZyyHdV9OCAnKRL5HrTQ4aODquEL8IAE/vPSrUyB5euG7ELDIbptor9pbleZ6OVMDtEI3KO8TWQq9H+UISWfMhbpXtBRsuxEv6aKarmaTCCvUwIRW4WFEIVuGFhHv6ev9iZZt7nt6l8RjxLwrJKVIaUBeH19fnmG+eKMXGyqUUkFqwWL6kIFCoXArXeoRN7XEG0+zYv94uzLwmwP/XbULCTHMX853113Fv0y0570RfzoCGUoXXL4xZKL0j1E+83XQOytivRXsuCtOuEoJ+vdZ8297HAEXL61LVCyWnH5PJsICYvXJm9JBp31IDO7QwLTFjjM8tQBU8OPge+UEFLgRMPFOg5QNR3o5CreddG8/IVfP33W6x/WDUbPH0y0OcQqtaw2/u3iLc+LIHA707mRzasDQZLsUc1Y4bUkQm0JbTYTdySgwybiwIVmXc4pgf/ESE1Jw/elAgeuvlevwTQxlnCWrVZoG0vnZLe7ZAtVWdb7ZLDMbugUOkTNKiR+lP0mXC+fsIhlhimrh0RPOVfRIpfrdQ3hGdyL9eyt/sgf3eHPKD0Xibf5NxmrRBUR4/59oSvk+SyumiWthSZ1kihcoOfcFXur0HEVovktqyuuAJaW0OdbKhnFSdWSc+xZwmbYriIhr6rccBOiFB+0p6jAW8DZBkUvU7Y+uMCd/EIGGJ94lWXK3d6+fNA1jdsGz/jmCCQiL8T2cIEU730h5VbGqca2uYsh8iieJaoV64tcmnEbLxGJ/99rs=
  template:
    metadata:
      name: graphql
      namespace: dev