apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.8.20
    helm:
      valuesObject: # TODO: insecure 옵션 제거 및 실제 ingress 설정
        server:
          extraArgs:
            - "--insecure"
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`argo.isitgone.site`) || Host(`argo.isitgone.local`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
