apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.8.20
    helm:
      valuesObject:
        server:
          extraArgs:
            - "--insecure"
          service:
            type: ClusterIP
        configs:
          rbac:
            scopes: '[email]'
            policy.default: role:none
            policy.csv: |
              g, ph38230119@gmail.com, role:admin
          cm:
            url: https://argo.isitgone.site
            admin.enabled: false
            dex.config: |
              connectors:
              - type: github
                id: github
                name: GitHub
                config:
                  clientID: <clientID>
                  clientSecret: <clientSecret>
                  redirectURI: https://argo.isitgone.site/api/dex/callback
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`argo.isitgone.site`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
