apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik # K3s 내장 Traefik HelmChart의 이름
  namespace: kube-system # K3s 내장 Traefik이 설치된 네임스페이스
spec:
  valuesContent: |-
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          certResolver: default
    # Let's Encrypt (ACME) Certificate Resolvers 설정
    # https://doc.traefik.io/traefik/https/acme/#certificate-resolvers
    # https://artifacthub.io/packages/helm/traefik/traefik?modal=values&path=certificatesResolvers
    
    # 현재 27.0.2 버전 traefik 사용 중
    # https://artifacthub.io/packages/helm/traefik/traefik?modal=values&compare-to=27.0.2
    # certificatesResolvers: # 최신 버전 필드이름
    certResolvers: 
      default:
        # acme: # 최신 버전
        email: ddiddhr@gmail.com # Let's Encrypt에서 인증서 만료 알림 등을 보낼 이메일
        storage: /data/acme.json

        httpChallenge:
          entryPoint: web # 80

          # Let's Encrypt 서버 설정
          # 초기 테스트 시에는 Staging 서버를 사용 권장 (Rate Limits 존재)
        # caServer: https://acme-staging-v02.api.letsencrypt.org/directory

    api:
      dashboard: false # default
      insecure: false # default
    healthcheck:
      enabled: true # default
    metrics:
      enabled: true # default
