spring-base:
  fullnameOverride: graphql
  nameOverride: graphql
  replicaCount: 3
  image:
    repository: ghcr.io/isitgone/graphql
    tag: 1.0.1
  resources:
    requests:
      memory: 256Mi
  livenessProbe:
    healthPath: /api/actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
  readinessProbe:
    healthPath: /api/actuator/health/readiness
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
  env:
    - name: DB_URI
      valueFrom:
        secretKeyRef:
          name: graphql
          key: DB_URI
  spring:
    profile: prod
    application:
      yml:
        spring:
          graphql:
            cors:
              allowed-origins: [ "https://web.isitgone.store" ]
              allowed-methods: [ "*" ]
              allowed-headers: [ "*" ]
              max-age: 1800
          application:
            name: graphql
          data:
            mongodb:
              uri: ${DB_URI}
        management:
          endpoints:
            web:
              exposure:
                include: health
              discovery:
                enabled: false
          endpoint:
            health:
              probes:
                enabled: true
              show-details: never
          health:
            defaults:
              enabled: false
            livenessState:
              enabled: true
            readinessState:
              enabled: true
