replicaCount: 3
image:
  repository: ghcr.io/isitgone/graphql
  tag: 0.0.0

ingress:
  host: isitgone.site

resources:
  requests:
    memory: 256Mi

env:
  - name: MONGODB_URI
    value: prod # TODO

spring:
  profile: prod
  application:
    yml:
      spring:
        application:
          name: graphql
        data:
          mongodb:
            uri: ${MONGODB_URI}