spring-base:
  fullnameOverride: graphql
  nameOverride: graphql
  replicaCount: 3
  image:
    repository: ghcr.io/isitgone/graphql
    tag: 1.0.0
  ingress:
    host: isitgone.site
  resources:
    requests:
      memory: 256Mi
  healthPath: /api/actuator/health
  env:
    - name: DB_URI
      valueFrom:
        secretKeyRef:
          name: graphql
          key: DB_URI
  spring:
    profile: prod
    application:
      yml:
        spring:
          application:
            name: graphql
          data:
            mongodb:
              uri: ${DB_URI}
        management:
          endpoints:
            web:
              exposure:
                include: health
              discovery:
                enabled: false
