spring-base:
  fullnameOverride: graphql
  nameOverride: graphql
  replicaCount: 1
  image:
    repository: ghcr.io/isitgone/graphql
    tag: e30256952a85f94d4498339d3e491460f725579d
  ingress:
    host: dev.isitgone.site
  resources:
    limits:
      memory: 256Mi
  healthPath: /api/actuator/health
  env:
    - name: DB_URI
      valueFrom:
        secretKeyRef:
          name: graphql
          key: DB_URI
  spring:
    profile: dev
    application:
      yml:
        spring:
          graphql:
            cors:
              allowed-origins: ["http://localhost:8080"]
              allowed-methods: ["*"]
              allowed-headers: ["*"]
              allow-credentials: true
              max-age: 1800
          application:
            name: graphql
          data:
            mongodb:
              uri: ${DB_URI}
        management:
          endpoints:
            web:
              exposure:
                include: health
              discovery:
                enabled: false
