spring-base:
  fullnameOverride: graphql
  nameOverride: graphql
  replicaCount: 1
  image:
    repository: ghcr.io/isitgone/graphql
    tag: 3d73861f18913aa3583ce0f5da989fc36605b4ff
  ingress:
    host: dev.isitgone.site
  resources:
    limits:
      memory: 256Mi
  livenessProbe:
    healthPath: /api/actuator/health/liveness
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 1
  readinessProbe:
    healthPath: /api/actuator/health/readiness
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 1
  env:
    - name: DB_URI
      valueFrom:
        secretKeyRef:
          name: graphql
          key: DB_URI
  spring:
    profile: dev
    application:
      yml:
        spring:
          graphql:
            cors:
              allowed-origins: ["https://dev.isitgone.site", "http://localhost:8080"]
              allowed-methods: ["*"]
              allowed-headers: ["*"]
              max-age: 1800
          application:
            name: graphql
          data:
            mongodb:
              uri: ${DB_URI}
        management:
          endpoints:
            web:
              exposure:
                include: health
              discovery:
                enabled: false
          endpoint:
            health:
              probes:
                enabled: true
              show-details: never
          health:
            defaults:
              enabled: false
            livenessState:
              enabled: true
            readinessState:
              enabled: true
