spring-base:
  fullnameOverride: graphql
  nameOverride: graphql
  replicaCount: 1
  image:
    repository: ghcr.io/isitgone/graphql
    tag: ac4ce5002adec18d04e903a480f26df0526bfa76
  ingress:
    host: dev.isitgone.site
  resources:
    limits:
      memory: 256Mi

  env:
    - name: DB_URI
      valueFrom:
        secretKeyRef:
          name: graphql
          key: DB_URI

  spring:
    profile: dev
    application:
      yml:
        spring:
          graphql:
            cors:
              allowed-origins: [ "http://localhost:8080" ]
              allowed-methods: [ "*" ]
              allowed-headers: [ "*" ]
              allow-credentials: true
              max-age: 1800
          application:
            name: graphql
          data:
            mongodb:
              uri: ${DB_URI}