name: Seal Secret

on:
  workflow_dispatch:

jobs:
  seal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install kubeseal
        run: |
          wget https://github.com/bitnami-labs/sealed-secrets/releases/latest/download/kubeseal-linux-amd64 -O kubeseal
          chmod +x kubeseal && sudo mv kubeseal /usr/local/bin/

      - name: Save sealed-secrets public key to file
        run: |
          echo "${{ secrets.SEAL_PUBLIC_KEY }}" > pub-cert.pem

      - name: Create Kubernetes Secret YAML from secret value
        run: |
          mkdir -p tmp/
          cat <<EOF > tmp/db-uri-secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: db-uri
            namespace: my-app
          type: Opaque
          stringData:
            uri: "${{ secrets.DEV_GRAPHQL_DB_URI }}"
          EOF

      - name: Generate SealedSecret
        run: |
          kubeseal \
            --cert=pub-cert.pem \
            --format=yaml \
            < tmp/db-uri-secret.yaml \
            > secrets/db-uri.sealed.yaml

      - name: Commit and push
        run: |
          git config user.name "ci-bot"
          git config user.email "ci@myorg.dev"
          git add secrets/db-uri.sealed.yaml
          git commit -m "chore: update sealed secret for db-uri"
          git push
